name: Juan Luis Guerra
description: Y 4.40
url: #place url
gems: [jekyll-paginate]
baseurl: /twister-jekyll-theme #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: /img
author_default_avatar: /profile-pic.jpg
tumblr: "#"
spotify: "https://open.spotify.com/artist/3nlpTZci9O5W8RsNoNH559"
instagram: "https://www.instagram.com/juanluisguerra/"
twitter: "https://twitter.com/JuanLuisGuerra"
facebook: "https://www.facebook.com/juanluisguerra440/"
youtube: "https://www.youtube.com/channel/UC5j34OS3TkHQyk4aPFiV5Sg"
vimeo: "https://vimeo.com/juanluisguerraoficial"
soundcloud: "https://soundcloud.com/juan-luis-guerra-official"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post_full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"

